experiment:
  seed: 42
  device: '0,1'
  name: 'test'

data:
  test_fasta_dir: './data/test.fasta'

  test_esm_input_pkl_dir: './data/'

  test_saprot_input_pkl_dir: './data/'

  test_meta_path: './data/test_metadata.csv'

  cls_num: 4443
  ec2num_dict_path: './data/ec_to_label.json'

  num_workers: 64

model:
  esm_arch: 'esm2_35m'
  saprot_arch: 'saprot_35m'

  use_fa: true

  saprot_model_dir: './ckpt/saprot_35m'  # path to the downloaded saprot model's directory

train:
  epochs: 50
  batch_size: 32

  lr: 0.00001
  weight_decay: 0.0001

  contrastive_weight: 1.0
  ec_weight: 1.0
  supcon_weight: 0.0

  val_interval: 1
  save_interval: 1

test:
  ckpt_path: './ckpt/deer_checkpoint.ckpt'
  save_result_dir: './result/'
